
# Get all mail messages for a specific server

@id = a03637c5f9a213a1474c93b083001d3de17aad88d34b92c3766cf105cdfdfb3d

GET {{base_url}}/api/v1/protocols/mail/{{id}}/messages
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36
Host: localhost:8000
Cache-Control: no-cache
Content-Type: application/json
Accept: */*

###

# Get all logs for a specific mail server

GET {{base_url}}/api/v1/protocols/mail/{{id}}/logs
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36
Host: localhost:8000
Cache-Control: no-cache
Content-Type: application/json
Accept: */*
