name: Docker Image CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Github Packages
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Get the tag
      run: echo "vartag=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/tim0-12432/simple-test-server:${{ env.vartag }}
    - name: Push the tagged Docker image
      run: docker push ghcr.io/tim0-12432/simple-test-server:${{ env.vartag }}
    - name: Build the latest Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/tim0-12432/simple-test-server:latest
    - name: Push the latest Docker image
      run: docker push ghcr.io/tim0-12432/simple-test-server:latest