name: Build and push Docker image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image name (repository)
        id: name
        run: |
          set -eux
          repo="${{ github.repository }}-2"
          echo "varname=${repo}" >> $GITHUB_OUTPUT

      - name: Set image tag (timestamp)
        id: tag
        run: |
          set -eux
          ts=$(date -u +"%Y%m%d-%H%M%S")
          echo "vartag=${ts}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ steps.name.outputs.varname }}:latest
            ghcr.io/${{ steps.name.outputs.varname }}:${{ steps.tag.outputs.vartag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Print pushed image
        run: |
          echo "Pushed: ghcr.io/${{ steps.name.outputs.varname }}:latest"
